version: "3.8"

services:
  gradio_chatbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: "http://model:8000/v1"
        MODEL: "${MODEL}"
    ports:
      - "7860:7860"
    links:
      - model

  model:
    image: ghcr.io/mistralai/mistral-src/vllm:latest
    environment:
      HF_TOKEN: "${HF_TOKEN}"
      MODEL: "${MODEL}"
    command: ["--host", "0.0.0.0", "--model", "${MODEL}", "--dtype", "half"] # Change to Bfloat16 if newer GPU
    volumes:
      - "./model/huggingface:/root/.cache/huggingface"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]